# Generated by Django 3.0.7 on 2020-07-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default='media/none/nothumb.jpg', upload_to=''),
        ),
    ]
