# Generated by Django 3.0.7 on 2020-07-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20200725_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default='none/nothumb.jpg', upload_to='courses'),
        ),
    ]
